### PR TITLE
global: update dependencies

### PR DESCRIPTION
**Pull request by utnapischtim**

### CODE REVIEW

**Comment by ThiefMaster** [comment]
nothing wrong with loosening the react version range but why *require* a higher version than actually needed? 

also, you're removing dependencies currently used in the tests...

**Comment by utnapischtim** [comment]
@ThiefMaster I created this PR to raise InvenioRDM to react 18.

> nothing wrong with loosening the react version range but why require a higher version than actually needed?
i understand your point. It is nothing wrong by stating only the minimal version which is necessary, but react v16 is way out of [end of life](https://endoflife.date/react) and using the caret syntax for dependencies prevents using the newest version (which is normally intended).
For me it seams better to move on to the currently supported react version.

> also, you're removing dependencies currently used in the tests...
Yes this is a mistake. I think there were problems on the updating process of all dependencies. I have to have a closer look at this problem.

**Comment by ThiefMaster** [comment]
Yes, react 16 can go for sure. 17 is still in use by us, so we need to keep this

**Comment by utnapischtim** [comment]
This means, i could update to v17 but not to v18?

**Comment by ThiefMaster** [comment]
I'd say `>=17` or something like that would be a good option. `>=16` would work as well.

**Comment by utnapischtim** [comment]
thanks. i will test that

**Pull request closed without merging**
