### PR TITLE
build: fix strict with babel runtime

### LINKED ISSUE #2: Remove strict mode for CommonJS build
When building the CommonJS dist, `rollup` automatically adds the `use strict` directive at the beginning of the generated `index.js`.
Not only this is not needed when CommonJS is exported with modules (see [here](https://eslint.org/docs/rules/strict)), but it also breaks JS when `Content-Security-Policies` is enabled.

Error:
```
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' ...
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'...
```

See explanation [here](https://github.com/facebook/regenerator/blob/master/packages/regenerator-runtime/runtime.js#L717)
```
  // This module should not be running in strict mode, so the above
  // assignment should always work unless something is misconfigured. Just
  // in case runtime.js accidentally runs in strict mode, we can escape
  // strict mode using a global Function call. This could conceivably fail
  // if a Content Security Policy forbids using Function, but in that case
  // the proper solution is to fix the accidental strict mode problem. If
  // you've misconfigured your bundler to force strict mode and applied a
  // CSP to forbid Function, and you're not willing to fix either of those
  // problems, please detail your unique predicament in a GitHub issue.
```

**Solution**
Change `rollup` to remove the `strict` directive.

### PR DESCRIPTION
**Pull request by ntarocco**
- closes #2

### CODE REVIEW

**Comment by ThiefMaster** [comment]
LGTM, what about adding a CHANGELOG file now that we'll make a second release?

**Comment by ntarocco** [comment]
Added a second commit with the changelog and the release.

**Comment by ThiefMaster** [comment]
> (!) Mixing named and default exports
> https://rollupjs.org/guide/en/#output-exports
> The following entry modules are using named and default exports together:
> src/index.js
>
> Consumers of your bundle will have to use chunk['default'] to access their default export, which > may not be what you want. Use `output.exports: 'named'` to disable this warning

Is this warning expected?

**Comment by ntarocco** [comment]
> > (!) Mixing named and default exports
> > https://rollupjs.org/guide/en/#output-exports
> > The following entry modules are using named and default exports together:
> > src/index.js
> > Consumers of your bundle will have to use chunk['default'] to access their default export, which > may not be what you want. Use `output.exports: 'named'` to disable this warning
> 
> Is this warning expected?

Thanks for spotting it, I didn't notice it in the output... it looks like that `auto` is not so smart in the end... :| Reverted it back to how was it before.

**Pull request merged**
